#!/usr/bin/perl
use feature say;
use HTML::Template;
use Image::ExifTool 'ImageInfo';
use Image::Magick::Thumbnail;
use File::Find;
use File::Basename;
use File::stat;
use Date::Format;
use Cwd 'abs_path';
use Config::IniFiles;

# OO interfaces
my $template;
my $exif = Image::ExifTool->new;
my $src = Image::Magick->new;

# Months
%monthnames = (
	'01' => "January",
	'02' => "February",
	'03' => "March",
	'04' => "April",
	'05' => "May",
	'06' => "June",
	'07' => "July",
	'08' => "August",
	'09' => "September",
	'10' => "October",
	'11' => "November",
	'12' => "December"
);

# A hash that reflects the configuration file
tie my %cfg, 'Config::IniFiles', (
	-file => "config.ini"
);

# Important directories in the source tree
$cfg{General}{BaseDir} = dirname(abs_path __FILE__). "/";
$cfg{General}{TemplateDir} = "$cfg{General}{BaseDir}tmpl/";
$cfg{WWW}{LocalPath} = "$cfg{General}{BaseDir}www/";

# Generated Thumbnails
$cfg{Thumbs}{LocalPath}= "$cfg{WWW}{LocalPath}thumbs/";
$cfg{Thumbs}{URL}= "$cfg{WWW}{URL}thumbs/";


# %images Stores information relating to your pictures
# e.g.
# %images = (
#	2018-March => [
#		(
#		IMG_SRC => 'someurl',
#		THUMB_SRC => 'someurl',
#		DATETIME => 'sometime',
#		),
#		(
#		IMG_SRC => 'someurl',
#		THUMB_SRC => 'someurl',
#		DATETIME => 'sometime',
#		),
#	],
#	2018-April => [
#		(
#		IMG_SRC => 'someurl',
#		THUMB_SRC => 'someurl',
#		DATETIME => 'sometime',
#		),
#	],
# );
my %images;

# Use File::Find to index an image
sub index_img {
	return if !-f;

	$infile = $File::Find::name;
	$exif->ExtractInfo($infile);
	# Interpret EXIF date metadata
	if ($exif->GetValue('DateTimeOriginal', 'PrintConv')) {
		$datestr = $exif->GetValue('DateTimeOriginal', 'PrintConv');
	} else {
		# Guess by the file mtime
		say "$File::Find::name lacks the DateTimeOriginal EXIF data";
		$mtime = stat($infile)->mtime;
		$datestr = time2str("%Y:%m:%d %H:%M:%S", $mtime);
	}
	# Break this timestamp into the year, month, and day
	$date = substr($datestr, 0, index($datestr, ' '));
	($year, $month, $day) = split(/:/, $date);
	$outfile = "$cfg{Thumbs}{LocalPath}$year-$month/$_";

	# Thumbnailing
	say "Thumbnailing: $_";
	mkdir "$cfg{Thumbs}{LocalPath}$year-$month";
	$src->Read($infile);
	($thumb, $tx, $ty) = Image::Magick::Thumbnail::create(
		$src, $cfg{General}{MaxThumbSize}
	);
	$thumb->Write($outfile);
	@$src = ();

	my %img_data;
	$img_data{THUMB_SRC} = "$cfg{Thumbs}{URL}$year-$month/$_";
	$img_data{IMG_SRC} = $cfg{Images}{URL} . substr(
		$File::Find::name, length($cfg{Images}{LocalPath})
	);
	$img_data{ALT_TEXT} = "$monthnames{$month} $day";
	$img_data{FIG_CAPTION} = "$monthnames{$month} $day";
	$img_data{THUMB_WIDTH} = $tx;
	$img_data{THUMB_HEIGHT} = $ty;
	push @{$images{"$year-$month"}}, \%img_data;
} find \&index_img, $cfg{Images}{LocalPath};

my @months;
# Creating pages for each month
foreach (sort keys %images) {
	my %month_data;
	($year, $month) = split(/-/, $_);
	$month_data{URL} = "$cfg{WWW}{URL}$_";
	$month_data{MONTH} = "$monthnames{$month} $year";
	$month_data{ALT_TEXT} = "$monthnames{$month} $year";
	$month_data{PCOUNTMSG} = @{$images{$_}};
	if ($month_data{PCOUNTMSG} > 1) {
		$month_data{PCOUNTMSG} .= " Photos" }
	else {
		$month_data{PCOUNTMSG} .= " Photo"
	}
	$sample = @{$images{$_}}[0];
	$month_data{COVER_SRC} = $sample->{THUMB_SRC};
	$month_data{COVER_WIDTH} = $sample->{THUMB_WIDTH};
	$month_data{COVER_HEIGHT} = $sample->{THUMB_HEIGHT};
	push @months, \%month_data;

	mkdir "$cfg{WWW}{LocalPath}$_";
	open $fh, ">", "$cfg{WWW}{LocalPath}$_/index.html";
	$template = HTML::Template->new(
		filename => "$cfg{General}{TemplateDir}month.html"
	);
	$template->param(IMAGE => $images{$_});
	$template->param(ROOT => $cfg{WWW}{URL});
	$template->param(DATE => "$monthnames{$month} $year");
	$template->param(PAGETITLE => "$monthnames{$month} $year");
	$template->output(print_to => $fh);
	close $fh;
}

# Creating the Index page
open $fh, ">", "$cfg{WWW}{LocalPath}index.html";
$template = HTML::Template->new(
	filename => "$cfg{General}{TemplateDir}index.html"
);
$template->param(MONTH => \@months);
$template->param(ROOT => $cfg{WWW}{URL});
$template->output(print_to => $fh);
close $fh;
